name: CI

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  report:
    needs:
      - lint-aux
      - extract-changelog
      - rustfmt
      - clippy
      - build-and-test
      - test-i586
      - build-no_std
      - check-generator
      - package-crate
    # '!cancelled()' is needed because GitHub treats a skipped job (due to a
    # failed dependency) a success.
    if: ${{ !cancelled() }}
    runs-on: ubuntu-24.04
    steps:
      - name: Report status
        env:
          NEEDS_JSON: ${{ toJson(needs) }}
        # Make sure all dependencies succeeded.
        run: jq --exit-status 'all(.result == "success")' <<< "$NEEDS_JSON"

  lint-aux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install lint utilities
        run: sudo npm install -g markdownlint-cli
      - name: Install Rust
        run: ./ci/install-rust.sh stable --profile minimal
      - run: ./ci/lint-aux.sh

  extract-changelog:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: ./ci/install-rust.sh stable --profile minimal
      - run: ./ci/extract-changelog.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-changelog
          path: version-changelog
          if-no-files-found: error

  rustfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: ./ci/install-rust.sh stable --profile minimal -c rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: ./ci/install-rust.sh stable --profile minimal -c clippy
      - run: ./ci/clippy.sh

  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - rust-version: msrv
          - rust-version: stable
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: ./ci/install-rust.sh "${{ matrix.rust-version }}" --profile minimal
      - run: ./ci/build-and-test.sh

  test-i586:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - rust-version: msrv
          - rust-version: stable
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-multilib
      - name: Install Rust
        run: |
          ./ci/install-rust.sh "${{ matrix.rust-version }}" --profile minimal \
            -t x86_64-unknown-linux-gnu \
            -t i586-unknown-linux-gnu
      - run: ./ci/test-i586.sh

  build-no_std:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: ./ci/install-rust.sh stable --profile minimal -t x86_64-unknown-none
      - run: ./ci/build-no_std.sh

  check-generator:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Sollya
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends sollya
      - name: Install Julia
        run: |
          wget "https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.9-linux-x86_64.tar.gz"
          sudo tar -xvf julia-1.10.9-linux-x86_64.tar.gz -C /opt
          echo "/opt/julia-1.10.9/bin" >> "$GITHUB_PATH"
      - name: Install Rust
        run: ./ci/install-rust.sh stable --profile minimal
      - run: ./ci/check-generator.sh

  package-crate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: ./ci/install-rust.sh stable --profile minimal
      - run: ./ci/package-crate.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-crate
          path: output
          if-no-files-found: error
